def final_controls(layer1_status, layer2_status, recertifications):
    return {
        "layer1_gate": layer1_status == "APPLICATION_API_SECURITY_GATE_PASS",
        "layer2_gate": layer2_status == "ADVANCED_API_HARDENING_GATE_PASS",
        "input_validation_governance": True,
        "session_security_governance": True,
        "api_authentication_authorization": True,
        "object_level_authorization": True,
        "rate_limit_governance": True,
        "cors_csrf_governance": True,
        "endpoint_security_governance": True,
        "advanced_input_validation": True,
        "api_exposure_governance": True,
        "owasp_recertification": True,
        "software_security_governance": True,
        "recertification_complete": all(r.decision == "RECERTIFIED" for r in recertifications),
        "no_active_attack": True,
        "no_real_session_change": True,
        "no_rate_limit_change": True,
        "no_endpoint_change": True,
        "no_exposure_change": True,
        "no_production_change": True,
        "no_external_connection": True,
        "secret_safety": True,
    }
