"""Persistencia PostgreSQL del Repositorio Léxico Base (RLB).

Este módulo define el foundation reproducible para materializar el
contrato RLB v1.1.0 en PostgreSQL.

No contiene credenciales y no abre conexiones durante importación.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Any

from .models import RegistroLexico


RLB_SCHEMA_VERSION = "1.1.0"
TABLE_NAME = "rlb_registro_lexico"

DDL = """
CREATE TABLE IF NOT EXISTS rlb_registro_lexico (
    pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    identificador TEXT UNIQUE,
    palabra_puinave TEXT NOT NULL,
    traduccion_espanol TEXT,
    traduccion_ingles TEXT,
    categoria_gramatical TEXT,
    categoria_tematica TEXT,

    tema_cultural TEXT,
    descripcion_cultural TEXT,
    contexto_uso TEXT,
    comunidad TEXT,
    territorio TEXT,

    imagen TEXT,
    audio_puinave TEXT,
    audio_espanol TEXT,
    audio_ingles TEXT,
    video TEXT,

    nivel_acceso TEXT NOT NULL DEFAULT 'pendiente_clasificacion',
    autorizacion_publicacion BOOLEAN NOT NULL DEFAULT FALSE,
    estado_validacion TEXT NOT NULL DEFAULT 'pendiente',

    origen JSONB,
    extensiones JSONB NOT NULL DEFAULT '{}'::jsonb,
    campos_desconocidos JSONB NOT NULL DEFAULT '[]'::jsonb,

    rlb_schema_version TEXT NOT NULL DEFAULT '1.1.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT rlb_registro_lexico_palabra_nonblank
        CHECK (btrim(palabra_puinave) <> '')
);


CREATE INDEX IF NOT EXISTS idx_rlb_registro_lexico_palabra
    ON rlb_registro_lexico (palabra_puinave);

CREATE INDEX IF NOT EXISTS idx_rlb_registro_lexico_estado
    ON rlb_registro_lexico (estado_validacion);
""".strip()


INSERT_SQL = """
INSERT INTO rlb_registro_lexico (
    identificador,
    palabra_puinave,
    traduccion_espanol,
    traduccion_ingles,
    categoria_gramatical,
    categoria_tematica,
    tema_cultural,
    descripcion_cultural,
    contexto_uso,
    comunidad,
    territorio,
    imagen,
    audio_puinave,
    audio_espanol,
    audio_ingles,
    video,
    nivel_acceso,
    autorizacion_publicacion,
    estado_validacion,
    origen,
    extensiones,
    campos_desconocidos,
    rlb_schema_version
)
VALUES (
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s,
    %s::jsonb, %s::jsonb, %s::jsonb, %s
)
ON CONFLICT (identificador) DO UPDATE SET
    palabra_puinave = EXCLUDED.palabra_puinave,
    traduccion_espanol = EXCLUDED.traduccion_espanol,
    traduccion_ingles = EXCLUDED.traduccion_ingles,
    categoria_gramatical = EXCLUDED.categoria_gramatical,
    categoria_tematica = EXCLUDED.categoria_tematica,
    tema_cultural = EXCLUDED.tema_cultural,
    descripcion_cultural = EXCLUDED.descripcion_cultural,
    contexto_uso = EXCLUDED.contexto_uso,
    comunidad = EXCLUDED.comunidad,
    territorio = EXCLUDED.territorio,
    imagen = EXCLUDED.imagen,
    audio_puinave = EXCLUDED.audio_puinave,
    audio_espanol = EXCLUDED.audio_espanol,
    audio_ingles = EXCLUDED.audio_ingles,
    video = EXCLUDED.video,
    nivel_acceso = EXCLUDED.nivel_acceso,
    autorizacion_publicacion = EXCLUDED.autorizacion_publicacion,
    estado_validacion = EXCLUDED.estado_validacion,
    origen = EXCLUDED.origen,
    extensiones = EXCLUDED.extensiones,
    campos_desconocidos = EXCLUDED.campos_desconocidos,
    rlb_schema_version = EXCLUDED.rlb_schema_version,
    updated_at = CURRENT_TIMESTAMP
RETURNING pk
""".strip()


def _json(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
    )


def registro_to_params(registro: RegistroLexico) -> tuple[Any, ...]:
    """Convierte RegistroLexico al contrato parametrizado PostgreSQL."""

    errores = registro.validar_minimo()
    if errores:
        raise ValueError("; ".join(errores))

    origen = asdict(registro.origen) if registro.origen is not None else None

    desconocidos = [
        asdict(item)
        for item in registro.campos_desconocidos
    ]

    return (
        registro.identificador,
        registro.palabra_puinave,
        registro.traduccion_espanol,
        registro.traduccion_ingles,
        registro.categoria_gramatical,
        registro.categoria_tematica,
        registro.tema_cultural,
        registro.descripcion_cultural,
        registro.contexto_uso,
        registro.comunidad,
        registro.territorio,
        registro.imagen,
        registro.audio_puinave,
        registro.audio_espanol,
        registro.audio_ingles,
        registro.video,
        registro.nivel_acceso,
        registro.autorizacion_publicacion,
        registro.estado_validacion,
        _json(origen),
        _json(registro.extensiones),
        _json(desconocidos),
        RLB_SCHEMA_VERSION,
    )


def ensure_schema(connection: Any) -> None:
    """Materializa el foundation RLB dentro de una transacción externa."""

    with connection.cursor() as cursor:
        cursor.execute(DDL)


def upsert_registro(connection: Any, registro: RegistroLexico) -> int:
    """Crea o actualiza idempotentemente un RegistroLexico por identificador."""

    if (
        registro.identificador is None
        or not registro.identificador.strip()
    ):
        raise ValueError(
            "identificador es obligatorio para persistencia idempotente."
        )

    params = registro_to_params(registro)

    with connection.cursor() as cursor:
        cursor.execute(INSERT_SQL, params)
        row = cursor.fetchone()

    if row is None:
        raise RuntimeError("PostgreSQL no devolvió PK para el registro.")

    return int(row[0])


def insert_registro(connection: Any, registro: RegistroLexico) -> int:
    """Compatibilidad: persiste mediante el UPSERT idempotente."""

    return upsert_registro(connection, registro)