[pytest]
testpaths = tests

norecursedirs =
    artifacts
    builder_backup
    builder_backup_*
    SGODA-PUINAVE
    .venv
    .pytest_cache
markers =
    capacity_120k: prueba de capacidad real con 120000 recursos multimedia