def final_controls(layer1_status, layer2_status, recertifications):
    return {
        "layer1_gate": layer1_status == "DATABASE_SECURITY_GOVERNANCE_GATE_PASS",
        "layer2_gate": layer2_status == "ADVANCED_DATABASE_GOVERNANCE_GATE_PASS",
        "database_access_governance": True,
        "secure_query_governance": True,
        "data_integrity_governance": True,
        "database_auditing_governance": True,
        "postgresql_hardening_governance": True,
        "persistence_governance": True,
        "roles_privileges_governance": True,
        "schema_security_governance": True,
        "migration_governance": True,
        "advanced_database_auditing": True,
        "transactional_integrity_governance": True,
        "persistence_protection_governance": True,
        "postgresql_advanced_governance": True,
        "recertification_complete": all(r.decision == "RECERTIFIED" for r in recertifications),
        "no_role_change": True,
        "no_schema_change": True,
        "no_migration_execution": True,
        "no_audit_configuration_change": True,
        "no_transaction_execution": True,
        "no_persistence_change": True,
        "no_postgresql_configuration_change": True,
        "no_external_connection": True,
        "secret_safety": True,
    }
