// GENERATED BY scripts/demo25/build_demo25_ui_config_driven.py
// Source of truth: instance-config.json + taxonomy.json + external-resources.json

const String demo25PlatformName = 'SGODA-PUINAVE';
const String demo25PlatformNameStatus =
    'PROVISIONAL_PENDING_COMMUNITY_CONFIRMATION';
const String demo25WebSiteName = 'SGODA-PUINAVE';
const String demo25WebPageTitle = 'SGODA-PUINAVE | Preservación y aprendizaje';
const String demo25WebShortName = 'SGODA-PUINAVE';
const String demo25AndroidAppName = 'SGODA-PUINAVE';
const String demo25InstitutionalSubtitle =
    'Preservación y aprendizaje de la lengua Puinave';
const String demo25CommunityName = 'Pueblo Puinave';
const String demo25NativeLanguageName = 'Puinave';
const String demo25Slogan =
    'Tecnología para preservar la memoria del pueblo Puinave.';
const String demo25VerifiedBibleUrl =
    'https://www.scriptureearth.org/00eng.php?iso=pui';

const List<Map<String, Object>> demo25SemanticCategoryCatalog = [
  {'id': 'family', 'label': 'Familia', 'enabled': true, 'order': 10},
  {'id': 'animals', 'label': 'Animales', 'enabled': true, 'order': 20},
  {'id': 'food', 'label': 'Alimentos', 'enabled': true, 'order': 30},
  {'id': 'actions', 'label': 'Acciones', 'enabled': true, 'order': 40},
  {'id': 'colors', 'label': 'Colores', 'enabled': true, 'order': 50},
  {'id': 'transport', 'label': 'Transporte', 'enabled': true, 'order': 60},
  {'id': 'body', 'label': 'Cuerpo humano', 'enabled': true, 'order': 70},
  {'id': 'health', 'label': 'Salud', 'enabled': true, 'order': 80},
  {'id': 'nature', 'label': 'Naturaleza', 'enabled': true, 'order': 90},
  {'id': 'agriculture', 'label': 'Agricultura', 'enabled': true, 'order': 100},
  {
    'id': 'communication',
    'label': 'Comunicación',
    'enabled': true,
    'order': 110,
  },
  {'id': 'materials', 'label': 'Materiales', 'enabled': true, 'order': 120},
  {'id': 'other', 'label': 'Por validar', 'enabled': true, 'order': 999},
];

Map<String, Object>? demo25SemanticCategoryConfig(String code) {
  final normalized = code.trim().toLowerCase();

  for (final item in demo25SemanticCategoryCatalog) {
    if ((item['id'] as String).toLowerCase() == normalized) {
      return item;
    }
  }

  return null;
}

bool demo25SemanticCategoryEnabled(String code) {
  final item = demo25SemanticCategoryConfig(code);

  if (item == null) {
    return false;
  }

  return item['enabled'] == true;
}

int demo25SemanticCategoryOrder(String code) {
  final item = demo25SemanticCategoryConfig(code);

  if (item == null) {
    return 999999;
  }

  return item['order'] as int? ?? 999999;
}

String demo25CategoryLabel(String code) {
  final normalized = code.trim().toLowerCase();

  if (normalized.isEmpty) {
    return 'Sin categoría';
  }

  final item = demo25SemanticCategoryConfig(normalized);

  if (item != null) {
    return item['label'] as String? ?? normalized;
  }

  final words = normalized
      .replaceAll('_', ' ')
      .replaceAll('-', ' ')
      .split(' ')
      .where((word) => word.isNotEmpty)
      .toList();

  if (words.isEmpty) {
    return 'Sin categoría';
  }

  return words
      .map(
        (word) => word.length == 1
            ? word.toUpperCase()
            : '${word[0].toUpperCase()}${word.substring(1)}',
      )
      .join(' ');
}

String demo25PublicStatus(String value) {
  switch (value.trim().toUpperCase()) {
    case 'VERIFIED':
      return 'Recurso verificado';

    case 'COMMUNITY_APPROVED':
      return 'Aprobado por la comunidad';

    case 'PENDING_VERIFICATION':
      return 'Pendiente de verificación';

    case 'READY_FOR_AUTHORIZED_CONTENT':
      return 'Preparado para contenido autorizado';

    case 'AVAILABLE':
      return 'Contenido disponible';

    case 'CONFIGURED':
      return 'Recurso configurado';

    case 'DERIVED_PENDING_VALIDATION':
      return 'Clasificación preliminar pendiente de validación';

    case 'PENDING_LINGUISTIC_VALIDATION':
      return 'Pendiente de validación lingüística';

    case 'PENDING':
      return 'Pendiente de validación';

    case 'INACTIVE':
      return 'Recurso inactivo';

    case 'PROVISIONAL_PENDING_COMMUNITY_CONFIRMATION':
      return 'Nombre provisional pendiente de confirmación comunitaria';

    default:
      return value.replaceAll('_', ' ').toLowerCase();
  }
}
