// GENERATED BY SGODA - DO NOT EDIT MANUALLY
// BIND-MULTILINGUAL-LIBRARY-CONVERSATIONS-TO-FLUTTER

const demo25NativeLanguageCode = 'pu';
const demo25NativeLanguageName = 'Puinave';

const demo25AuxLanguages = <Map<String, String>>[
  {'code': 'es', 'name': 'Español', 'availability': 'AVAILABLE_IN_REAL25'},
  {'code': 'en', 'name': 'English', 'availability': 'PENDING_CONTENT'},
  {'code': 'it', 'name': 'Italiano', 'availability': 'PENDING_CONTENT'},
  {'code': 'pt', 'name': 'Português', 'availability': 'PENDING_CONTENT'},
];

const demo25SemanticCategories = <String, Map<String, String>>{
  'PU-000001': {
    'semantic': 'family',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000002': {
    'semantic': 'animals',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000003': {
    'semantic': 'food',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000004': {
    'semantic': 'family',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000005': {
    'semantic': 'food',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000006': {
    'semantic': 'food',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000007': {
    'semantic': 'actions',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000008': {
    'semantic': 'actions',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000009': {
    'semantic': 'actions',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000010': {
    'semantic': 'actions',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000011': {
    'semantic': 'materials',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000012': {
    'semantic': 'communication',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000013': {
    'semantic': 'communication',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000014': {
    'semantic': 'transport',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000015': {
    'semantic': 'animals',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000016': {
    'semantic': 'animals',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000017': {
    'semantic': 'actions',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000018': {
    'semantic': 'colors',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000019': {
    'semantic': 'colors',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000020': {
    'semantic': 'colors',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000021': {
    'semantic': 'agriculture',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000022': {
    'semantic': 'health',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000023': {
    'semantic': 'animals',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000024': {
    'semantic': 'animals',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
  'PU-000025': {
    'semantic': 'body',
    'semanticStatus': 'DERIVED_PENDING_VALIDATION',
    'grammatical': '',
    'grammaticalStatus': 'PENDING_LINGUISTIC_VALIDATION',
  },
};

const demo25LibraryResourceTypes = <Map<String, String>>[
  {'id': 'BIBLE', 'title': 'Biblia'},
  {'id': 'DICTIONARY', 'title': 'Diccionario'},
  {'id': 'EDUCATIONAL_MATERIAL', 'title': 'Material educativo'},
  {'id': 'PHOTOGRAPHIC_ARCHIVE', 'title': 'Registro fotográfico'},
  {'id': 'DOCUMENTARY_INTERVIEW', 'title': 'Documentales y entrevistas'},
  {'id': 'NATIVE_CONVERSATION', 'title': 'Conversaciones de hablantes nativos'},
  {'id': 'AUDIO_ARCHIVE', 'title': 'Archivo sonoro'},
  {'id': 'VIDEO_ARCHIVE', 'title': 'Archivo de video'},
  {'id': 'CULTURAL_RESOURCE', 'title': 'Recursos culturales'},
  {'id': 'OTHER', 'title': 'Otro'},
];

const demo25LibraryResources = <Map<String, String>>[
  {
    'id': 'puinave-bible',
    'type': 'BIBLE',
    'title': 'Biblia en Puinave',
    'description': 'Recurso bíblico disponible en lengua Puinave.',
    'status': 'VERIFIED',
    'visible': 'true',
    'url': 'https://www.scriptureearth.org/00eng.php?iso=pui',
  },
  {
    'id': 'puinave-photographic-archive',
    'type': 'PHOTOGRAPHIC_ARCHIVE',
    'title': 'Registro fotográfico Puinave',
    'description': 'Colección configurable para fotografías relacionadas con la lengua, comunidad, territorio y patrimonio Puinave.',
    'status': 'PENDING_VERIFICATION',
    'visible': 'false',
    'url': '',
  },
  {
    'id': 'puinave-documentary-interviews',
    'type': 'DOCUMENTARY_INTERVIEW',
    'title': 'Documentales, testimonios y entrevistas Puinave',
    'description': 'Colección audiovisual configurable de documentales, testimonios y entrevistas a hablantes y miembros de la comunidad.',
    'status': 'PENDING_VERIFICATION',
    'visible': 'false',
    'url': '',
  },
];

const demo25ConversationCount = 0;
