from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

repo = Path(sys.argv[1]).resolve()

instance_path = (
    repo / "config" / "demo25" / "instances" / "puinave"
    / "instance-config.json"
)

taxonomy_path = instance_path.parent / "taxonomy.json"
resources_path = instance_path.parent / "external-resources.json"

support_path = (
    repo / "apps" / "sgoda_puinave_demo" / "lib"
    / "demo25_ui_closure_support.g.dart"
)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def dart_string(value: Any) -> str:
    if value is None:
        value = ""

    value = str(value)

    value = value.replace("\\", "\\\\")
    value = value.replace("'", "\\'")
    value = value.replace("$", "\\$")
    value = value.replace("\r", " ")
    value = value.replace("\n", " ")

    return "'" + value + "'"


instance = read_json(instance_path)
taxonomy = read_json(taxonomy_path)
resources = read_json(resources_path)

identity = instance.get("identity", {})
web = instance.get("web", {})
android = instance.get("android", {})

instance_block = instance.get("instance", {})
community = instance_block.get("community", {})
native = instance_block.get("native_language", {})

platform_name = identity.get(
    "platform_name",
    "SGODA-PUINAVE",
)

platform_status = identity.get(
    "platform_name_status",
    "PROVISIONAL_PENDING_COMMUNITY_CONFIRMATION",
)

subtitle = identity.get(
    "institutional_subtitle",
    "",
)

slogan = identity.get(
    "slogan",
    "",
)

community_name = community.get(
    "name",
    "",
)

native_language_name = native.get(
    "name",
    "",
)

web_site_name = web.get(
    "site_name",
    platform_name,
)

web_page_title = web.get(
    "page_title",
    platform_name,
)

web_short_name = web.get(
    "short_name",
    platform_name,
)

android_app_name = android.get(
    "app_name",
    platform_name,
)

semantic = taxonomy.get(
    "semantic_categories",
    [],
)

if not isinstance(semantic, list) or not semantic:
    raise RuntimeError(
        "SEMANTIC_CATEGORY_CATALOG_EMPTY"
    )

catalog = []

for item in semantic:

    if not isinstance(item, dict):
        raise RuntimeError(
            "SEMANTIC_CATEGORY_ENTRY_INVALID"
        )

    category_id = str(
        item.get("id", "")
    ).strip()

    label = str(
        item.get("label_es", "")
    ).strip()

    enabled = bool(
        item.get("enabled", False)
    )

    order = int(
        item.get("order", 999)
    )

    if not category_id:
        raise RuntimeError(
            "SEMANTIC_CATEGORY_ID_EMPTY"
        )

    if not label:
        raise RuntimeError(
            "SEMANTIC_CATEGORY_LABEL_EMPTY="
            + category_id
        )

    catalog.append(
        {
            "id": category_id,
            "label": label,
            "enabled": enabled,
            "order": order,
        }
    )

catalog.sort(
    key=lambda item: (
        item["order"],
        item["label"].casefold(),
        item["id"],
    )
)

bible_url = ""

def walk(value: Any):

    global bible_url

    if isinstance(value, dict):

        resource_type = str(
            value.get("type", "")
        ).upper()

        status = str(
            value.get("status", "")
        ).upper()

        url = value.get("url")

        if (
            resource_type == "BIBLE"
            and status == "VERIFIED"
            and isinstance(url, str)
            and url.startswith(
                ("https://", "http://")
            )
        ):
            bible_url = url.strip()

        for child in value.values():
            walk(child)

    elif isinstance(value, list):

        for child in value:
            walk(child)


walk(resources)

support = (
    "// GENERATED BY scripts/demo25/"
    "build_demo25_ui_config_driven.py\n"
    "// Source of truth: instance-config.json "
    "+ taxonomy.json + external-resources.json\n\n"
)

support += (
    "const String demo25PlatformName = "
    + dart_string(platform_name)
    + ";\n"
)

support += (
    "const String demo25PlatformNameStatus = "
    + dart_string(platform_status)
    + ";\n"
)

support += (
    "const String demo25WebSiteName = "
    + dart_string(web_site_name)
    + ";\n"
)

support += (
    "const String demo25WebPageTitle = "
    + dart_string(web_page_title)
    + ";\n"
)

support += (
    "const String demo25WebShortName = "
    + dart_string(web_short_name)
    + ";\n"
)

support += (
    "const String demo25AndroidAppName = "
    + dart_string(android_app_name)
    + ";\n"
)

support += (
    "const String demo25InstitutionalSubtitle = "
    + dart_string(subtitle)
    + ";\n"
)

support += (
    "const String demo25CommunityName = "
    + dart_string(community_name)
    + ";\n"
)

support += (
    "const String demo25NativeLanguageName = "
    + dart_string(native_language_name)
    + ";\n"
)

support += (
    "const String demo25Slogan = "
    + dart_string(slogan)
    + ";\n"
)

support += (
    "const String demo25VerifiedBibleUrl = "
    + dart_string(bible_url)
    + ";\n\n"
)

support += (
    "const List<Map<String, Object>> "
    "demo25SemanticCategoryCatalog = [\n"
)

for item in catalog:

    support += "  {\n"
    support += (
        "    'id': "
        + dart_string(item["id"])
        + ",\n"
    )
    support += (
        "    'label': "
        + dart_string(item["label"])
        + ",\n"
    )
    support += (
        "    'enabled': "
        + (
            "true"
            if item["enabled"]
            else "false"
        )
        + ",\n"
    )
    support += (
        "    'order': "
        + str(item["order"])
        + ",\n"
    )
    support += "  },\n"

support += "];\n\n"

support += r"""
Map<String, Object>? demo25SemanticCategoryConfig(
  String code,
) {
  final normalized = code.trim().toLowerCase();

  for (final item in demo25SemanticCategoryCatalog) {
    if ((item['id'] as String).toLowerCase() == normalized) {
      return item;
    }
  }

  return null;
}

bool demo25SemanticCategoryEnabled(String code) {
  final item = demo25SemanticCategoryConfig(code);

  if (item == null) {
    return false;
  }

  return item['enabled'] == true;
}

int demo25SemanticCategoryOrder(String code) {
  final item = demo25SemanticCategoryConfig(code);

  if (item == null) {
    return 999999;
  }

  return item['order'] as int? ?? 999999;
}

String demo25CategoryLabel(String code) {
  final normalized = code.trim().toLowerCase();

  if (normalized.isEmpty) {
    return 'Sin categoría';
  }

  final item = demo25SemanticCategoryConfig(normalized);

  if (item != null) {
    return item['label'] as String? ?? normalized;
  }

  final words = normalized
      .replaceAll('_', ' ')
      .replaceAll('-', ' ')
      .split(' ')
      .where((word) => word.isNotEmpty)
      .toList();

  if (words.isEmpty) {
    return 'Sin categoría';
  }

  return words
      .map(
        (word) => word.length == 1
            ? word.toUpperCase()
            : '${word[0].toUpperCase()}${word.substring(1)}',
      )
      .join(' ');
}

String demo25PublicStatus(String value) {
  switch (value.trim().toUpperCase()) {
    case 'VERIFIED':
      return 'Recurso verificado';

    case 'COMMUNITY_APPROVED':
      return 'Aprobado por la comunidad';

    case 'PENDING_VERIFICATION':
      return 'Pendiente de verificación';

    case 'READY_FOR_AUTHORIZED_CONTENT':
      return 'Preparado para contenido autorizado';

    case 'AVAILABLE':
      return 'Contenido disponible';

    case 'CONFIGURED':
      return 'Recurso configurado';

    case 'DERIVED_PENDING_VALIDATION':
      return 'Clasificación preliminar pendiente de validación';

    case 'PENDING_LINGUISTIC_VALIDATION':
      return 'Pendiente de validación lingüística';

    case 'PENDING':
      return 'Pendiente de validación';

    case 'INACTIVE':
      return 'Recurso inactivo';

    case 'PROVISIONAL_PENDING_COMMUNITY_CONFIRMATION':
      return 'Nombre provisional pendiente de confirmación comunitaria';

    default:
      return value
          .replaceAll('_', ' ')
          .toLowerCase();
  }
}
"""

support_path.write_text(
    support,
    encoding="utf-8",
)

print(
    "CONFIG_DRIVEN_SUPPORT_GENERATED=PASS"
)

print(
    "SEMANTIC_CATEGORY_CATALOG="
    + str(len(catalog))
)

print(
    "BIBLE_VERIFIED_URL="
    + (
        "BOUND"
        if bible_url
        else "VERIFIED_URL_PENDING_BINDING"
    )
)

print(
    "PUBLIC_IDENTITY_CONFIG_BIND_SOURCE=PASS"
)

print(
    "TAXONOMY_CONFIG_BIND_SOURCE=PASS"
)